//
// Created by jay on 6/2/21.
//

#ifndef J5C_INSTALL_FROM_SOURCE_001_TYPE_ABBREVIATIONS_H
#define J5C_INSTALL_FROM_SOURCE_001_TYPE_ABBREVIATIONS_H

using sstr = std::string;

#endif //J5C_INSTALL_FROM_SOURCE_001_TYPE_ABBREVIATIONS_H
